# Checkout a github repo and use refspec to fetch all pull requests
- hosts: local
  become: true
  tasks:
    - name: fetch repo for hello-world
      git:
       repo: https://github.com/talal-shobaita/hello-world.git
       dest: /opt/hello-world
       refspec: '+refs/pull/*:refs/heads/*'

    - name: deploy service hello-world 
      command: chdir=/opt/hello-world/ {{ item }}
      with_items:
       - mvn package
       - mvn spring-boot:run
